### ISSUE TITLE
Cannot use constants as patterns

### ISSUE THREAD

**Issue by sanmai-NL** [hyperium/mime#53]
```
error: to use a constant of type `hyper::<unnamed>::Mime` in a pattern, `hyper::<unnamed>::Mime` must be annotated with `#[derive(PartialEq, Eq)]`
   --> src/lib.rs:560:33
    |
560 |                                 TEXT_HTML => ".html",
    |                                 ^^^^^^^^^
```
(I'm not sure whether I can make time soon for a small PR.)

**Comment by seanmonstar** [comment]
I know, deriving PartialEq for Mime is not possible, it has to deal with optional whitespace differences and parameter orders.

**Comment by sanmai-NL** [comment]
Could you elaborate a bit? 

In your [writeup on the new API](https://github.com/hyperium/mime/pull/50#issue-234324812) you noted that this type of match is still possible:
```Rust
match (mime.type_(), mime.subtype()) {
    (mime::TEXT, mime::PLAIN) => println!("plain text"),
    (mime::TEXT, _) => println!("structured text"),
    _ => println!("not text"),
}
```
So as I understand it is necessary to compare a `Mime` value by deconstructing it? Okay then. Not sure though whether whitespace differences or parameter orders should have any meaning for equivalence. Can't they be ignored?

**Comment by seanmonstar** [comment]
Yes, sorry, I should have said more.

You can compare by equality with `Mime`s. `some_mime == mime::TEXT_PLAIN` is perfectly valid. However, due to the equality requirements in the spec, a `derive(PartialEq)` cannot work. A derived `PartialEq` will compare strings literally. The spec says whitespace and parameter order are irrelevant. Here's examples that must be equal:

- `text/plain; chartset=utf-8` and `text/plain;charset=utf-8 `
- `multipart/form-data; charset=base64; boundary=foobar` and `multipart/form-data; boundary=foobar; charset=base64`

That does prevent pattern matching on the constants of `Mime`.

**Comment by sanmai-NL** [comment]
Okay, but what I didn't know was that you [did implement](https://github.com/hyperium/mime/blob/fda8cf121a1e2da06959f3185e3dd9bfdec64234/src/lib.rs#L323-L337) `PartialEq` for `Mime`. So `rustc` demands that `PartialEq` must be derived for any type to be used in a pattern. I do not understand why.

**Comment by seanmonstar** [comment]
Ah, this is why: https://github.com/rust-lang/rfcs/blob/master/text/1445-restrict-constants-in-patterns.md

It does seem like the error could be improved, especially when the type is not from your library. You have no control over adding a `derive(PartialEq)`, and so it shouldn't tell you that is needed. It should clarify that the type cannot be used in patterns, and that's it (imo).
