### ISSUE TITLE
Handling quoted-string parameter values correctly

### ISSUE THREAD

**Issue by rustonaut** [hyperium/mime#67]
Parameter values can be quoted strings which:
1. can be empty (currently rejected) 
2. ~can contain escape sequences (e.g. `\"`) (currently rejected)~
   handle escape sequences correctly

At last fixing the later one can cause a problem with `Name::is_str(&self) -> str`,
which is not returning the underlying string representation (it strips the quotes).
But neither is it returning the content as a string as it can not unescape the
escape sequences. You still can treat it as always returning the inner part
of the value as quoted string, which would be correct, but I fear people won't do that.

---

For the next braking release I would have following idea:
1. remove `Name::is_str` (or better have `Name` for names and `Value` for values and do not have `is_str` on `Value`)
2. introduce `str_repr(&self) -> &str` returning the underlying str representation _including quotes_ if there had been any, this is nice if you e.g. can only allow ascii values as you now do not need to recheck them if they are not quoted
3. introduce `to_content_str(&self) -> Cow<'a, str>` which:
   1. returns `Borrowed(self.str_repr())` if it's not quoted
   2. returns `Borrowed(&self.str_repr()[1..self.str_repr().len()-1])` (+- optimiz) for quoted value not containing escape sequences
   3. returns `Owned(unquoteself.str_repr()))` which returns the string represented by the quoted-string by undoing any quoting escapes etc.

**Comment by dathinab** [comment]
If this is considered a good solution I can work on this and make a pull request.

The question would be:
- go the full way (Name=> Name+Value, etc.) which is a braking change
- or add `str_repr` + `to_content_str` to `Name` braking changes can be done later together with others needed for the 1.0 release

Uh, I guess we should go with the second choice?

**Comment by dathinab** [comment]
It also probably should be decided if `PartialEq<str>` compares the underlying representation or the actual content.

E.g. is mime parameter `a="abc"` equal to `abc` or `"abc"` or both, and what is with `"\a\b\c"`

I would go with what currently is more or less the case, a content based eq comparsion, i.e.
the param of `a="abc"`, `a=abc`, `a="\a\b\c"` are all equals `abc` but not e.g. `\a\b\c` as the content does not contain any escapes, only the representation does.

**Comment by seanmonstar** [comment]
Why can't `Name::as_str` return the contents if the string is quoted? This should probably be made to work:

```rust
let mime: Mime = "text/plain; foo=bar; baz=\"quux\"".parse().unwrap();
assert_eq!(mime.get_param("foo").unwrap(), "bar");
assert_eq!(mime.get_param("baz").unwrap(), "quux");
```

**Comment by dathinab** [comment]
Because it _would not be the content, but a partial representation_ and would easily lead to bugs.
The only reason why it currently works is because the parser wrongfully rejects quoted-pairs
in quoted-strings (something similar to  `\` escapes).

The content of `foo` in `a/b; foo="b\ ar"` is `b ar` _not_ `b\ ar`.
But the representation of foo is `"b\ ar"` but could also be e.g. `"\b ar"`.

As you do not want to introduce any unnecessary allocs `Name::as_str` would still return `&str`
which means it can not unquote quoted strings correctly as it can only remove the encapsulating 
quotes but not unquote quoted pairs. 

But it's also not  returning the representation. And even if, many people would probably not be aware of
the fact that it does so and would thing that if `get_param("foo").unwrap() == "bar"` then `get_param("foo").unwrap().as_str() == "bar"` _but this would not hold up_ if `bar` was
represented as e.g. `"b\ar"`.

So not having `as_str` is to help people to not shoot themself in the foot when it comes to less commen mim-type parameter values.

---
Also there is no reason why your example should not work, you just can't implement `PartialEq<str>` with `as_str`. What basically should work is:

```rust
let mime: Mime = r#"text/plain; foo=bar; baz="quux"; foo2="a\ b\"c"; foo3="\abc"; foo4=abc"#.parse().unwrap();
assert_eq!(mime.get_param("foo").unwrap(), "bar");
assert_eq!(mime.get_param("baz").unwrap(), "quux");
assert_eq!(mime.get_param("foo2").unwrap(), r#"a b"c"#);
assert_eq!(mime.get_param("foo3").unwrap(), "abc");
assert_eq!(mime.get_param("foo4").unwrap(), "abc");
assert_eq!(mime.get_param("foo3"), mime.get_param("foo4"));

//things which should fail
//here the content is "\abc" which would be represented by "\\abc"
assert_ne!(mime.get_param("foo3").unwrap(), "\abc");
```

**Comment by dathinab** [comment]
Uh, I just noticed that the current version does parse escape sequences in the code, either I messed up when testing or it was fixed at some point.

Nevertheless it's still not handling it in a ~acceptable~ good way wrt. `as_str`.

**Comment by dathinab** [comment]
It also accepts `"\\"` ( halve a quoted pair ) which is not a valid quoted-string.
(while is is slightly ambiguous in the definition appearing in the rfc for HTTP/1.1 
it is much more clearly defined in other RFC's.

**Comment by seanmonstar** [comment]
This has been merged into master and will be released very soon.
